### ISSUE TITLE
distutils recognises version as 0.0.0 instead of the correct 1.2.0

### ISSUE THREAD

**Issue by badshah400** [scikit-hep/hepunits#19]
When building and installing hepunits (I am trying to build packages for openSUSE), setuptools seems to copy the egg-info dir into `/usr/lib/python3.8/site-packages/hepunits-0.0.0-py3.8.egg-info` instead of the correct `/usr/lib/python3.8/site-packages/hepunits-1.2.0-py3.8.egg-info`. Probably some issue with distutils reading the pkg version.

Attempts to build packages for openSUSE at <https://build.opensuse.org/package/show/home:badshah400:branches:science/python-hepunits>, but I also attach the full build log here.
[_log.zip](https://github.com/scikit-hep/hepunits/files/5027646/_log.zip)

Thanks for your massively useful library, btw.

**Comment by henryiii** [comment]
If you build from source, you need to install `setuptools_scm`. If you use `pip` or `pep517.build` instead of directly running `setup.py` (which is highly discouraged in modern Python packaging), it does this for you. If you install from the universal wheel instead, you do not need anything extra.

**Comment by henryiii** [comment]
It looks like you can get it for opensuse here:

https://build.opensuse.org/package/view_file/devel:languages:python/python-setuptools_scm/python-setuptools_scm.spec?expand=1

So I think you can just require it? (really only is needed at build time)

**Comment by badshah400** [comment]
Thanks for the quick response. I put in a `BuildRequires` for `python-setuptools_scm` but that seems to have not done the trick (egg-info still recognises the version as 0.0.0). See [the same page](https://build.opensuse.org/package/show/home:badshah400:branches:science/python-hepunits) for updated build results.

**Comment by henryiii** [comment]
Is this being built with Python3 or Python2? I notice in the `setuptools_scm` there is some logic for supporting either one (even though it is noarch too), while I don't see similar logic here, and I see a warning about a usage of `python2` in the logs.

I think we could improve the situation here by adding a `import setuptools_scm` line in setup.py, which would make sure you get the correct error, rather than just getting a 0.0.0 version. We could instead put manual version discovery in setup.py, since the version file is present in the source tarball - but that is a bit of a hack, while the correct solution is to properly set up the build environment if using the source file instead of the wheel.

**Comment by henryiii** [comment]
By the way, since you are manually setting the version in the .spec file anyway, you could set `SETUPTOOLS_SCM_PRETEND_VERSION=%{version}`. Also, should this be:

```
Source:         https://files.pythonhosted.org/packages/source/h/%{modname}/%{modname}-%{version}.tar.gz
```

for simpler updating later?

**Comment by henryiii** [comment]
Ahh, found the problem. I thought this:

```
Suggests:       python-toml
```
was `Requires`. It needs this package too to read the `pyproject.toml` to know where the version is.

**Comment by badshah400** [comment]
It's set up to build for both python2 and python3 for openSUSE_Leap_15.x (which still support both versions of python) and only python3 for openSUSE_Tumbleweed (rolling distro that no longer supports python2). The macros help figure this out (so when it reports python2 missing, it only builds for python3 and so on).

Adding `BuildRequires:  %{python_module toml}` did the trick (in addition to `python-setuptools_scm`). Thank you.

**Comment by henryiii** [comment]
I've merged #20, which would have made this much easier to diagnose, I believe. I think we should likely do a 1.2.1 with this in the near future.

**Comment by henryiii** [comment]
Oh, one more thing - what version of setuptools are you using? I think 42+ will automatically install the pyproject.toml requirements - this manual addition is only needed for setuptools < 42.

**Comment by badshah400** [comment]
Using different setuptools versions:
* 44.0 for Tumbleweed
* 40.5 for Leap 15.x.

I hope you don't mind my abusing this bug report with another question I have (I'll open a separate issue if you think it merits one). When building against python2, this error crops up:

```
[    8s] running egg_info
[    8s] error: 'egg_base' must be a directory name (got `src`)
[    8s] error: Bad exit status from /var/tmp/rpm-tmp.IOIVdc (%build)
```

Am I missing any python2 specific requirements? Thanks again for all your help.

**Comment by henryiii** [comment]
This is a bug that was fixed in setuptools 40.7.

**Comment by henryiii** [comment]
If you want to move this line from setup.cfg into setup.py, you can keep it from becoming Unicode. I'd probably just patch it.

**Comment by henryiii** [comment]
Okay, great, I see you've fixed it. We do require setuptools 42+ generally, so that looks like a reasonable fix due to lockin to an older version.

**Comment by badshah400** [comment]
Yeah, I moved the installed egg-info dir around for the older openSUSEs. That should be all right, I think.
