### ISSUE TITLE
Wheel

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/hepunits#2]
Please add a wheel; currently, you cannot simply install hepunits with `--target` into a directory with `/tests`, since it's bundling tests in the SDist and no wheel is available. Adding a setup.cfg for universal wheels would be nice, as would publishing from CI. But I mostly need the wheel, for an existing version is just fine.

**Comment by henryiii** [comment]
Edit: You have a __init__.py in your tests directory, and tests is not excluded for  find_packages, so it picks up tests as a package! That needs to be fixed as well; probably needs a small patch release.

**Comment by eduardo-rodrigues** [comment]
Closed with https://github.com/scikit-hep/hepunits/pull/3.
