### ISSUE TITLE
Typo when converting radian to degree.

### ISSUE THREAD

**Issue by dengbangjie** [scikit-hep/hepunits#7]
Should line [L226](https://github.com/scikit-hep/hepunits/blob/a91becfa45751ee6542e6cdd5a1dcb6407a26558/hepunits/units/units.py#L226)
```
degree = (pi / 180.) * radian
```
be
```
degree = (180. / pi) * radian
```
?

Self-doubting ...

**Comment by dengbangjie** [comment]
I'm wrong. Sorry.

**Comment by jpivarski** [comment]
Yup. When converting from radians, you have to take the pi out and put the 180 in. (How I always have to remember it.)

**Comment by HDembinski** [comment]
I like to think of degree and radian as different units, just like "seconds" and "gram". Just pretend that Pi is a unit and degree is another unit. Then you do the conversion as usual, you first divide by the unit you want to remove and multiply with the target unit.
